language: ruby
rvm:
  - 2.1.4
env:
  global:
    - DISPLAY=":99.0"
before_install:
  - gem source -u
  - npm install bower -g
before_script:
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake bower:install
script:
  - bundle exec rake
bundler_args: --without development production assets
