language: ruby
rvm:
  - 2.3.1
env:
  global:
    - CHROME_BIN=chromium-browser
    - DISPLAY=":99.0"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - gem source -u
  - npm install bower -g
before_script:
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake bower:install
script:
  - bundle exec rake
bundler_args: --without development production assets
