sudo: required
language: ruby
dist: trusty
addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
rvm:
  - 2.3.1
env:
  global:
    - DISPLAY=":99.0"
    - CHROME_BIN="/usr/bin/google-chrome"
    - PATH=$PATH:./bin/
before_install:
  - gem source -u
  - npm install bower -g
before_script:
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake bower:install
script:
  - bundle exec rake
bundler_args: --without development production assets
